baseurl = "https://www.skipoliva.com/"
title = "S.M. Oliva, LLC"
copyright = "Copyright &copy; 2016-2018 - S.M. Oliva, LLC - [CC-BY-NC](http://creativecommons.org/licenses/by-nc/4.0/)"
canonifyurls = true
theme = "kiera"

paginate = 5

summaryLength = 30
enableEmoji = false
pygmentsCodeFences = true

[author]
    name = "S.M. Oliva"
    github = "oswriter"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "Blog Ghostwriting + Legal Content Services"
